= Understand the Agent Visualizer Components

Agent Visualizer shows how your agent network is structured. Explore node types such as brokers, agents, and MCP servers, and edges that show declared and runtime relationships and traffic. Use layers and filters to focus your view, and detail cards to see metadata and metrics.

[[nodes]]
== Node Types

There are different types of nodes in the agent network to provide a visual representation of different agentic assets (agents, brokers, and MCP servers) within the agent network. Nodes show you the structure, interactions, health, and governance of distributed agents, brokers, and MCP servers. 

• Broker nodes
+
Represent broker groups and enumerate the different broker agents they can communicate with. Broker groups are defined in the broker YAML and published to Anypoint Exchange.
• Agents
+
These nodes represent agents that perform specific functionality and include these types:
+
** Agentforce agents
+
Agents that originate from Agentforce 
** External agents
+
Agents that originate from external, non-Salesforce platforms, such as OpenAI, Bedrock, Vertex AI, and so on 
** Brokers
+
Brokers originate from MuleSoft and are referenced in the agent network YAML
• MCP servers
+
These nodes represent MCP (Model Context Protocol) servers.

In the Agent Visualizer graph, nodes show icons and labels, indicating their type (agent, broker, or MCP server), name, and protection status at a glance. 

Selecting a node opens the Inspector Panel, which provides detailed information about the node.

=== Node Details

When you select a node, a detail card opens to provide comprehensive information for the asset.

[NOTE]
Broker metadata is defined in the agent network YAML. For more information about creating an agent network project, see xref:anypoint-code-builder::index.adoc[].

[%header,cols="30a,70a"]
|===
| Field | Description
| Name | Name of the asset. 
| Description | Description of the asset.
|Provider | Provider of the asset.
| Platform | Platform of the asset, for example, Agentforce or MuleSoft.
| LLM | LLM provider (for example, `openai` or `einstein`).
| Linked Agents | List of agents that are linked to the broker. 
|MCP Servers and Tools | List of MCP servers and tools that are connected to the broker.
| Enabled Capabilities | Lists the capabilities that are supportted by the agent. 
| Instance Name | Instance name as it appears in API Manager.
| Environment Type | Lists the environments the instance is deployed to, for example, `sandbox` or `production`.
| Based on Asset Version | The version of the instance. 
| Policies | Lists the policies that are applied to the instance.
| Governance and Security | Shows whether the asset is protected by a Flex Gateway.
| Performance and Health | Shows the performance and health metrics for the instance.
| Monitoring | Provides links to logs and traces for quick access to troubleshooting tools. 
| Tags| All the tags associated with the asset in Exchange.
|===

[[edges]]
== Edges

Edges represent the relationships and communications among your nodes. 

You can see two types of edges: 

* Declared edges appear between node instances when there is no runtime information available because there's no registered traffic among them. These are shown as dashed lines on the graph.
* Runtime edges are shown between nodes when traffic is registered and a Flex Gateway exists. Solid lines on the graph indicate runtime edges. Clicking on a runtime edge opens the detail panel and shows the relevant metrics.

Edges are drawn under specific conditions, primarily when the calling agent is protected by a Flex Gateway at egress.

* If an agent has an egress Flex Gateway, when it calls another agent the edge is visible.
* If the requesting agent doesn't have an egress Flex Gateway, no edge metric is generated and the edge isn't shown.
* Broker agents that route outbound calls through an egress Flex Gateway, allowing requests between broker agents, or from a broker agent to an external agent, appear in the agent network visualization.

=== Edge Metadata

When you click on an edge, the detail panel displays relationship information and metrics.

* Source Node ID
* Target Node ID
* Edge type (YAML/Runtime)
* Call volume (which can be represented visually by thicker or dotted lines)
* Number of conversations (1 day)
* Token consumption
* Policy violations count
* Errors
* Latency

== Data Flow Layers

Data flow layers are used to group nodes in the agent network visualization. They help you highlight specific types of nodes in the visualization.

* Production Data Flow Layer
+
This is the default view. It shows all agentic assets that are published in Anypoint Exchange, declared edges (design-time relationships), and production traffic (live connections).
* Non-Production Traffic Layer    
+
You can choose to turn on the non-production traffic layer to see non-production traffic (test and sandbox connections). 

[[filters]]
== Filters

Filters help you narrow the data set that's shown, helping you focus on the most relevant information.

You can filter by: 

* Environment
* Agent type
* Platform

[[details-card]]
== Details Cards

The details card is the primary means for gaining detailed, 360-degree information about a selected node or edge. It includes metadata about the node or edge and links to relevant resources like logs, policies, and more.

[[policy-visualization]]
== Policy Visualization

The policy visualization enables you to see nodes that are protected by a Flex Gateway at a glance. Nodes that are protected by a Flex Gateway are shown with a shield icon. Data about applied policies comes from API Manager.

You can see the details of applied policies in detail card for the selected node. 

== See Also

* xref:index.adoc[]
* xref:view-and-navigate-agent-network.adoc[]
* xref:monitoring::index.adoc[]
* xref:api-manager::index.adoc[]
* xref:anypoint-exchange::index.adoc[]
