= Node Governance

You can use the visual indicators in the agent network visualization to assess the security and compliance status of your agents.

[[viewing-node-policies]]
== Viewing Node Policies

. Look for the shield icon on nodes to see which nodes are secured by Flex Gateways.
. Click the node to open the detail card and see the policies that are applied to the node.
. Click *View Policies* to view the policies for this instance in API Manager.
+
Policies are listed by category on the left and applied policies are listed on the right. 

[[adding-a-flex-gateway]]
== Adding a Flex Gateway

. Click the node to open the detail card and see the policies that are applied to the node.
. Click *Add Flex Gateway*. 
. In API Manager, add an instance of the asset (MCP server, broker, or agent) to protect.
+
For information about adding an MCP server instance, see xref:flex-gateway::create-instance-task-mcp[]. For information adding an A2A instance, see xref:flex-gateway::create-instance-task-a2a[].

== See Also

* xref:index.adoc[]
* xref:view-and-navigate-agent-network.adoc[]
* xref:flex-gateway::index.adoc[]
