= Troubleshooting Your Agent Network

Agent Visualizer gives you quick access to tools to troubleshoot your agent network.

[[view-metrics]]
== View Metrics

. Select a node to open the detail card.
. In *Performance and Health*, click *View metrics* to view additional metrics in Anypoint Monitoring. 

For more information, see xref:monitoring::anypoint-insights-agentic.adoc[].

[[access-logs]]
== Access Logs

On US and EU Clouds, Anypoint Monitoring aggregates log files so you can manage, search for, filter, and analyze your logs. You can use aggregated logs in conjunction with monitoring to help identify issues and investigate failures quickly. 

. Click the node to open the detail card.
. Click *View Logs* to access the logs for the node.
+
You are taken to Anypoint Monitoring where you can view the logs for the asset instance. For more information see xref:monitoring::logs-us-eu.adoc#search-agentic[Get Agent, Broker, and MCP Server Logs].

[[access-traces]]
== Access Traces

Use Traces in Anypoint Monitoring to track the flow of requests that travel through service pipelines. Examine traces in Open Telemetry (OTEL) spans to troubleshoot requests that have errors or slow response times, optimize your resource allocation, and track requests end-to-end. 

. Click the node to open the detail card.
. Click *View Traces* to access the traces for the node.
+
Anypoint Monitoring opens and you can view the *Traces Details* page for the asset instance. 

== See Also

* xref:monitoring::logs.adoc[]
* xref:monitoring::traces.adoc[]
