= Agent Network Visualization

When viewing the Agent Visualizer graph, you can:

* Zoom in and out. 
* Click and drag on the canvas to pan the visualization.
* Search for the name of an asset on the canvas and the nodes that contain your search will be highlighted.

[[nodes]]
== Nodes

Nodes are the visual representation of different agentic assets (agents, brokers, and MCP servers) within the agent network. Nodes show you the structure, interactions, health, and governance of distributed agents, brokers, and MCP servers. 

• Brokers
+
Represent MuleSoft broker groups and enumerate the different broker agents they can communicate with. Broker groups are defined in the broker YAML and published to Anypoint Exchange.
• Agents
+
These nodes represent agents capable of performing specific functionalities. They can be of different types:
** Agentforce agents
+
Originate from Agentforce 
** External agents
+
Originate from third-party platforms 
** Broker agents
+
Originate from MuleSoft and are referenced in a broker group YAML
• MCP Servers
+
These nodes represent MCP (Model Context Protocol) servers.

In the Agent Visualzier graph, nodes show icons and labels, indicating their type (agent, broker, or MCP server), name, and protection status at a glance. Selecting a node opens the Inspector Panel, which provides detailed information about the node.


[[edges]]
== Edges

Edges represent the relationships and communications between your nodes. You can see two types of edges: 

* Declared edges appear between node instances when there is no runtime information available because there's no registered traffic between them. These are shown as dashed lines on the graph.
**Runtime edges are shown between nodes when traffic is registered and a Flex Gateway is exists. Runtime edges are displayed as solid lines on the graph.

[[policy-visualization]]
== Policy Visualization

The policy visualization enables you to see nodes that are protected by a Flext Gateway at a glance. which policies have been applied to assets. Nodes that are protected by a Flex Gateway are shown with a shield icon. Data about applied policies comes from API Manager.